// import {KayakPOM} from '../pages/KayakPOM'

import { parse } from "path"
import { browser, element, by, ExpectedConditions } from "protractor"
// import { BrowserStack } from "protractor/built/driverProviders"

const KayakPOM = require('../pages/KayakPOM')
describe('Kayak Flight Test', function(){
    beforeEach(function(){
        browser.get('https://www.kayak.com')
        browser.driver.manage().window().maximize();
        KayakPOM.setFlightTab()
        KayakPOM.clickFlightTab()
    })
    it('Test Origin Exist', function(){
        KayakPOM.setOrigin()
        KayakPOM.isOriginDisplayed()
    })
    it('Test Destination Exist', function(){
        KayakPOM.setDestination()
        KayakPOM.isDestinationDisplayed()
    })
    it('Test Departure Field Exist',function(){
        KayakPOM.setDepartureDate()
        KayakPOM.isDepartureDateDisplayed()
    })
    it('Test Return Field Exist',function(){
        KayakPOM.setReturnDate()
        KayakPOM.isReturnDateDisplayed()
    })
    it('Trip Type Test', async function(){
        KayakPOM.setTripType()
        let result = await KayakPOM.getTripTypeDataAttribute()
        expect(result).toBe('roundtrip')    
    })
    it('Set Trip Type Oneway Test',async function(){
        KayakPOM.setTripType()
        KayakPOM.tripType.click()
        KayakPOM.setOneway()
        KayakPOM.clickOneway()
        let result = await KayakPOM.getTripTypeDataAttribute()
        expect(result).toBe('oneway')
    })
    it('Set Trip Type Multi-City Test', async function(){
        KayakPOM.setTripType()
        KayakPOM.clickTripType()
        KayakPOM.setMultiCity()
        KayakPOM.clickMultiCity()
        let result = await KayakPOM.getTripTypeDataAttribute()
        expect(result).toBe('multicity')
    })
    it('Set Trip Type Round Trip Test', async function(){
        KayakPOM.setTripType()
        KayakPOM.clickTripType() 
        KayakPOM.setRoundTrip()
        KayakPOM.clickRoundTrip()   
        let result = await KayakPOM.getTripTypeDataAttribute()
        expect(result).toBe('roundtrip')
    })
    it("Adult Count Test", async function(){
        KayakPOM.setTravelerInfo()
        KayakPOM.clickTravelerInfo()
        KayakPOM.setAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.setAdultCountError()
        let result = await KayakPOM.getAdultCountError()
        expect(result).toBe('Searches cannot have more than 9 adults')
        browser.sleep(3000)
    })
    it('Origin Test PAR', async function(){
        browser.sleep(1000)
        KayakPOM.setOriginCancelBtn()
        KayakPOM.clickOriginCancelBtn()
        browser.sleep(1000)
        KayakPOM.setOriginAirport()
        KayakPOM.sendOriginText('PAR')
        browser.sleep(1000)
        KayakPOM.setOriginOpt()
        KayakPOM.clickOriginOpt()
        browser.sleep(1000)
        KayakPOM.setOrigin()
        let result = await KayakPOM.getOriginValue()
        expect(result).toBe('PAR')
    })
    it('Origin Test NYC', async function(){
        browser.sleep(1000)
        KayakPOM.setOriginCancelBtn()
        KayakPOM.clickOriginCancelBtn()
        browser.sleep(1000)
        KayakPOM.setOriginAirport()
        KayakPOM.sendOriginText('NYC')
        browser.sleep(1000)
        KayakPOM.setOriginOpt()
        KayakPOM.clickOriginOpt()
        browser.sleep(1000)
        KayakPOM.setOrigin()
        let result = await KayakPOM.getOriginValue()
        expect(result).toBe('NYC')
    })
    it('Travel Label Test', async function(){
        KayakPOM.setTravelerInfo()
        KayakPOM.clickTravelerInfo()
        KayakPOM.setAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        browser.sleep(1000)
        KayakPOM.setTravelLabel()
        let result = await KayakPOM.getTravelLabelValue()
        expect(result).toBe('4 Travelers')
    })
    //Step 9
    it('Travel Label Test', async function(){
        KayakPOM.setTravelerInfo()
        KayakPOM.clickTravelerInfo()
        KayakPOM.setAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.clickAdultCountIncreaseBtn()
        KayakPOM.setChildIncreaseBtn()
        KayakPOM.clickChildIcreaseBtn()
        KayakPOM.clickChildIcreaseBtn()
        browser.sleep(1000)
        KayakPOM.setTravelLabel()
        let result = await KayakPOM.getTravelLabelValue()
        expect(result).toBe('6 Travelers')
    })
    //step 13
    it('Check Cheap Best Quick', async function(){
        KayakPOM.setDestination()
        KayakPOM.clickDestination()
        browser.sleep(1000)
        KayakPOM.setDestinationAirport()
        KayakPOM.sendDestinationAirportValue('Paris (PAR)')
        browser.sleep(2000)
        KayakPOM.setDestinationOpt()
        KayakPOM.clickDestinationOpt()
        browser.sleep(1000)
        KayakPOM.setSearchBtn()
        KayakPOM.clickSearchBtn()
        let e = KayakPOM.setCheapestPrice()
        browser.wait(ExpectedConditions.presenceOf(e),50000).then(async ()=>{
            browser.sleep(6000)
            let cheapestPrice :string = await KayakPOM.getCheapestPrice()
            const cheapestPriceResult:Number = parseInt(cheapestPrice.slice(1,))
            KayakPOM.setBestPrice()
            const bestPrice:string = await KayakPOM.getBestPrice()
            const bestPriceResult:Number = parseInt(bestPrice.slice(1,))
            KayakPOM.setQuickestPrice()
            const quickestPrice:string = await KayakPOM.getQuickestPrice()
            const quickestPriceResult = parseInt(quickestPrice.slice(1,))
            browser.sleep(2000)
            console.log('cheapestPrice=> ',cheapestPriceResult)
            console.log('bestPrice=> ',bestPriceResult)
            console.log('quickestPrice',quickestPriceResult)
            expect(cheapestPriceResult < bestPriceResult && cheapestPriceResult < quickestPriceResult).toBeTruthy()
        })
    })
})